textEN = {
    'lan':'English',
    'lanOption':'English',
    'lanMenu':'Language',
    'title':'Petoi Controller for OpenCat',
    'Model':'Model',
    'Exit':'Exit',
    'Help':'Help',
    'About':'About',
    'Repeat':'Repeat',
    'Loop':'Loop',
    'Frame':'Frame',
    'Step':'Step',
    'Delay':'Delay',
    'Trig':'Trigger',
    'Angle':'Angle',
    'Note':'Note',
    'Del':'Del',
    'Add':'Add',
    'Set':'Set',
    'Save':'Save',
    'Stop':'Stop',
    'Joint Controller':'Joint Controller',
    'Unbind All':'Unbind All',
    'Yaw':'Yaw',
    'Pitch':'Pitch',
    '-Pitch':'-Pitch',
    'Roll':'Roll',
    '-Roll':'-Roll',
    'Spinal':'Spinal',
    'Height':'Height',
    'Sideway':'Sideway',
    'Head Pan':'Head Pan',
    'Head Tilt':'Head Tilt',
    'Tail Pan':'Tail Pan',
    'N/A':'N/A',
    'Left Front':'Left Front',
    'Right Front':'Right Front',
    'Right Back':'Right Back',
    'Left Back':'Left Back',
    'Shoulder':'Shoulder',
    'Arm':'Arm',
    'Knee':'Knee',
    'State Dials':'State Dials',
    'Connect':'Connect',
    'Connected':'Connected',
    'Listening':'Listening',
    'All':'All',
    'None':'None',
    'Servo':'Servo',
    'Gyro':'Gyro',
    'Random':'Random',
    'tipConnect':'Keep updating the active serial\nports until it\'s disabled',
    'tipPortMenu':'Control single or all of the devices',
    'tipServo':'Activate/deactivate the servos',
    'tipGyro':'Activate/deactivate the gyroscope',
    'tipRandom':'Activate/deactivate the random behaviors\n* in certain modes',
    'Postures':'Preset Postures',
    'Scheduler':'Scheduler',
    'Play':'Play',
    'Import':'Import',
    'Restart':'Restart',
    'tipRestart':'Clear all the frames in the scheduler!',
    'Export':'Export',
    'tipExport':'The skill will be sent in real time and saved\nin the static memory of the robot\nUse serial token \'T\' to call the last sent skill',
    'Undo':'Undo',
    'Redo':'Redo',
    'Open File':'Open File',
    'Cancel':'Cancel',
    'Ok':'Ok',
    'exampleFormat':'Import from files, or copy & paste the skill data from instinct.h in the following format.\n* Keep the curly brackets!',
    'Quit':'Quit',
    'Do you want to quit?':'Do you want to quit?',
    'mirror':'      MirrorAll',
    '>|<':'>|<',
    'Gait':'  Gait',
    'Behavior':'  Behavior',
    'tipGorB':'A behavior interpolates between the key frames and excutes only once\nA gait loops over all the frames without any smoothing',
    'Clear':'Clear',
    'max':'max',
    '':'',
    'tipBinder':'Bind to other joints',
    'tipRevBinder':'Reversely bind to other joints',
    'tipMirror':'Mirror the current frame',
    'tipMirrorXport':'Mirror the whole skill when exporting\n* Effective when exporting the whole skill',
    'tipLoop':'Set the starting and ending frames for looping\n* Effective when exporting the whole skill',
    'tipRepeat':'Enter the number of loops\n* Effective when exporting the whole skill',
    'tipSet':'Jump to/save the current frame',
    'tipStep':'Unit: degree/step',
    'tipDelay':'Unit: milisecond',
    'tipTrig':'Trigger the next frame only when the body rolls\nover the triggering angle in a certain direction\n* Effective when exporting the whole skill',
    'tipTrigAngle':'The critical angle for the trigger',
    'tipNote':'Give the frame an easy to remember name',
    'tipAdd':'Copy the current frame and\ninsert it to the next row',
    'tipDel':'Delete the current frame',
}
textCN = {
    'lan':'Chinese',
    'lanOption':'中文',
    'lanMenu':'语言',
    'title':'派拓艺 OpenCat 上位机',
    'Model':'产品',
    'Exit':'退出',
    'Help':'帮助',
    'About':'关于',
    'Repeat':'重复',
    'Loop':'循环',
    'Frame':'帧',
    'Step':'速度',
    'Delay':'延时',
    'Trig':'触发轴',
    'Angle':'触发角',
    'Note':'标记',
    'Del':'删除',
    'Add':'添加',
    'Set':'设置',
    'Save':'保存',
    'Stop':'停止',
    'Joint Controller':'关节控制器',
    'Unbind All':'取消所有绑定',
    'Yaw':'偏航',
    'Pitch':'俯仰',
    '-Pitch':'逆俯仰',
    'Roll':'横滚',
    '-Roll':'逆横滚',
    'Spinal':'脊向',
    'Height':'高度',
    'Sideway':'侧向',
    'Head Pan':'头部平转',
    'Head Tilt':'头部俯仰',
    'Tail Pan':'尾巴平转',
    'N/A':'闲置',
    'Left Front':'左前',
    'Right Front':'右前',
    'Right Back':'左后',
    'Left Back':'右后',
    'Shoulder':'肩',
    'Arm':'臂',
    'Knee':'膝',
    'State Dials':'状态开关',
    'Connect':'连接',
    'Connected':'已连接',
    'Listening':'检测中',
    'All':'全部',
    'None':'无',
    'Servo':'舵机',
    'Pause':'暂停',
    'Gyro':'陀螺仪',
    'Random':'随机行为',
    'tipConnect':'持续更新活跃串口列表直到被挂起',
    'tipPortMenu':'控制单个或所有设备',
    'tipServo':'启用或禁用舵机',
    'tipGyro':'启用或禁用陀螺仪',
    'tipRandom':'启用或禁用随机动作\n* 只在某些模式下',
    'Postures':'预设姿态',
    'Scheduler':'时序器',
    'Play':'运行',
    'Import':'导入',
    'Restart':'重置',
    'tipRestart':'清空时序器中的所有帧！',
    'Export':'导出',
    'tipExport':'技能会实时发送并保存在机器人的静态内存\n可以通过串口指令\'T\'调用上次发送的技能',
    'Undo':'撤消',
    'Redo':'重复',
    'Open File':'打开文件',
    'Cancel':'取消',
    'Ok':'确认',
    'exampleFormat':'从文件导入，或以下列格式从 instinct.h 复制粘贴技能数组。\n* 保留大括号!',
    'Quit':'退出',
    'Do you want to quit?':'要退出吗?',
    'mirror':'      镜像导出',
    '>|<':'>|<',
    'Gait':'   步态',
    'Behavior':'   行为',
    'tipGorB':'行为给关键帧插值并只执行一轮\n步态循环执行所有帧并且不加平滑处理',
    'Clear':'清空',
    'max':'最快',
    'tipBinder':'绑定其他关节',
    'tipRevBinder':'反绑其他关节',
    'tipMirror':'镜像当前帧',
    'tipMirrorXport':'导出整个技能的镜像\n* 在导出整体技能时生效',
    'tipLoop':'选择循环的起止帧\n* 在导出整体技能时生效',
    'tipRepeat':'输入循环次数\n* 在导出整体技能时生效',
    'tipSet':'跳入/保存当前帧',
    'tipStep':'单位：度/步长',
    'tipDelay':'单位：毫秒',
    'tipTrig':'当机身以特定方向越过触发角时触发下一帧\n* 在导出整体技能时生效',
    'tipTrigAngle':'触发临界角',
    'tipNote':'给当前帧起一个便于记忆的名字',
    'tipAdd':'复制当前帧并插入到下一行',
    'tipDel':'删除当前帧',
}

textFR={
    'lan':'French',
    'lanOption':'Français',
    'lanMenu':'Langue',
    'Model':'Maquette',
    'Exit':'Sortie',
    'Help':'Aider',
    #to be finished
}
textJP={
    'lan':'Japanese',
    'lanOption':'日语',
    'lanMenu':'语言',
    'Model':'モデル',
    'Exit':'出口',
    'Help':'ヘルプ',
    #to be finished
}

textIT = {
    'lan':'Italiano Italian',
    'lanOption':'Italian',
    'lanMenu':'Lingua',
    'title':'Petoi Controllo per OpenCat',
    'Model':'Modello',
    'Exit':'Uscita',
    'Help':'Aiuto',
    'About':'Chi siamo',
    'Repeat':'Ripeti',
    'Loop':'Loop',
    'Frame':'Quadro',
    'Speed':'Velocita',
    'Delay/ms':'Ritardo/ms',
    'Trig':'Trigger',
    'Angle':'Angolo',
    'Note':'Nota',
    'Del':'Canc',
    'Add':'Aggingi',
    'Set':'Set',
    'Save':'Salva',
    'Stop':'Stop',
    'Joint Controller':'Controllo multiplo',
    'Yaw':'Yaw',
    'Pitch':'Pitch',
    'roll':'Roll',
    'Head Pan':'Head Pan',
    'Head Tilt':'Head Tilt',
    'Tail Pan':'Tail Pan',
    'N/A':'N/A',
    'Shoulder Left Front':'Shoulder\nLeft Front',
    'Shoulder Right Front':'Shoulder\nRight Front',
    'Shoulder Right Back':'Shoulder\nRight Back',
    'Shoulder Left Back':'Shoulder\nLeft Back',
    'Arm Left Front':'Arm\nLeft Front',
    'Arm Right Front':'Arm\nRight Front',
    'Arm Right Back':'Arm\nRight Back',
    'Arm Left Back':'Arm\nLeft Back',
    'Knee Left Front':'Knee\nLeft Front',
    'Knee Right Front':'Knee\nRight Front',
    'Knee Right Back':'Knee\nRight Back',
    'Knee Left Back':'Knee\nLeft Back',
    'State Dials':'State Dials',
    'Connect':'Connetti',
    'Pause':'Pausa',
    'Gyro':'Gyro',
    'Random':'Random',
    'Postures':'Posizioni Preset',
    'Scheduler':'Sequenza',
    'Play':'Start',
    'Import':'Importa',
    'Restart':'Restart',
    'Export':'Esporta',
    'Undo':'Undo',
    'Redo':'Redo',
    'Open File':'Apri File',
    'Cancel':'Cancel',
    'Ok':'Ok',
    'exampleFormat':'Importa skill data da instinct.h nel seguente formato:',
    'Disconnect':'Disconnetti',
    'Connect':'Connetti',
    'Pause':'Pausea',
    'Paused':'In pausa',
    'Gyro:OFF':'Gyro:OFF',
    'Gyro: ON':'Gyro: ON',
    'Random:OFF':'Random:OFF',
    'Random: ON':'Random: ON',
    'Quit':'Esci',
    'Do you want to quit?':'Vuoi uscire ?',
    'Mirror':'Specchio',
    'Gait':'Cammina',
    'Behavior':'Comportamento',
    'Clear':'Clear',
}

languageList = {
    'English':textEN,
    'Chinese':textCN,
    'Italian':textIT,
    'French':textFR,
    'Japanese':textJP,
    #to be added
}
