textEN = {
    'lan':'English',
    'lanOption':'English',
    'lanMenu':'Language',
    'uiTitle':'Petoi Desktop App',
    'calibTitle':'Joint Calibrator',
    'skillComposerTitle':'Petoi Skill Composer for OpenCat',
    'Model':'Model',
    'Utility':'Utility',
    'Joint Calibrator':'Joint Calibrator',
    'Skill Composer':'Skill Composer',
    'Task Scheduler':'Task Scheduler',
    'Scheduler':'Scheduler',
    'Firmware Uploader':'Firmware Uploader',
    'Exit':'Exit',
    'Help':'Help',
    'About':'About',
    'Repeat':'Repeat',
    'Loop':'Loop',
    'Frame':'Frame',
    'Step':'Step',
    'Delay':'Delay',
    'Trig':'Trigger',
    'Angle':'Angle',
    'Note':'Note',
    'Del':'Del',
    'Add':'Add',
    'Set':'Set',
    'Save':'Save',
    'Stop':'Stop',
    'Joint Controller':'Joint Controller',
    'Unbind All':'Unbind All',
    'Yaw':'Yaw',
    'Pitch':'Pitch',
    '-Pitch':'-Pitch',
    'Roll':'Roll',
    '-Roll':'-Roll',
    'Spinal':'Spinal',
    'Height':'Height',
    'Sideway':'Sideway',
    'Head Pan':'Head Pan',
    'Head Tilt':'Head Tilt',
    'Tail Pan':'Tail Pan',
    'N/A':'N/A',
    'Left Front':'Left Front',
    'Right Front':'Right Front',
    'Right Back':'Right Back',
    'Left Back':'Left Back',
    'Shoulder':'Shoulder',
    'Arm':'Arm',
    'Knee':'Knee',
    'State Dials':'State Dials',
    'Connect':'Connect',
    'Connected':'Connected',
    'Listening':'Listening',
    'All':'All',
    'None':'None',
    'Servo':'Servo',
    'Gyro':'Gyro',
    'Random':'Random',
    'Postures':'Preset Postures',
    'Skill Editor':'Skill Editor',
    'Play':'Play',
    'Import':'Import',
    'Restart':'Restart',
    'Export':'Export',
    'Undo':'Undo',
    'Redo':'Redo',
    'Open File':'Open File',
    'Cancel':'Cancel',
    'Ok':'Ok',
    'exampleFormat':'Import from files, or copy & paste the skill data from instinct.h in the following format.\n* Keep the curly brackets!',
    'Quit':'Quit',
    'Do you want to quit?':'Do you want to quit?',
    'mirror':'      MirrorAll',
    '>|<':'>|<',
    'Gait':'  Gait',
    'Behavior':'  Behavior',
    'Clear':'Clear',
    'max':'max',
    
    'Calibration':'Calibration',
    'Stand Up':'Stand Up',
    'Rest':'Rest',
    'Abort':'Abort',
    'Do you want to save the offsets?':'Do you want to save the offsets?',
    'uploaderTitle': 'Flash uploader',
    'labTrans': 'Change Language',
    'labChi': 'Chinese',
    'labEng': 'English',
    'labHelp': 'Help',
    'labAbout': 'About',
    'labExit': 'Exit',
    'labFileDir': 'Choose the release folder',
    'btnFileDir': '...',
    'titleFileDir': 'Please choose the release folder',
    'labPort': 'Serial port',
    'labSoftwareVersion': 'Software version',
    'labBoardVersion': 'Board version',
    'labProduct': 'Product',
    'labMode': 'Mode',
    'rbnWalk': 'Walk',
    'rbnUltrasonic': 'Ultrasonic',
    'rbnCamera': 'Camera',
    'Parameters':'Parameters',
    'Main function':'Main function',
    'btnUpload': 'Upload',
    'titleWarning': 'Warning',
    'Uploading': 'Uploading ',
    'is successully uploaded':' is successully uploaded',
    'failed to upload':' failed to upload',

    'msgFileDir': 'Please choose the release folder!',
    'msgPort': 'Please choose the correct serial port!',
    'titleVersion': 'Version information',
    'msgVersion': '''Version: 1.0.0
    Flash upload tool for OpenCat
    Copyright © 2018-2022
    All rights reserved
    Petoi LLC
    https://www.petoi.com\n
    ''',
    'reset joints?': 'Reset joint offsets? (Y/N)',
    'reseting joints': 'Reset joint offsets...',
    'joints reset': 'Reset joint offsets complete!',
    
    'update instincts?':'Update Instinct? (Y/n)',
    'updating instincts':'Updating Instincts......',
    'instincts updated': 'instincts updated',
    
    'calibrate IMU?':'''Calibrate IMU? (Y/N)
    Note: Lay the robot FLAT on a table!''',
    'calibrating IMU': 'Calibrating IMU...',
    'IMU calibrated': 'Calibrate IMU complete!',
    
    
    'parameterFinish': 'Parameters initialized!',
    'msgFinish': 'Firmware upload complete!',
    'msgMode': 'Invalide, please select another mode!',


    'Standard':'Standard',
    'Random_Mind':'Random_Mind',
    'Ultrasonic':'Ultrasonic',
    'Voice':'Voice',
    'Camera':'Camera',

    '':'',
    'tipConnect':'Keep updating the active serial\nports until it\'s disabled',
    'tipPortMenu':'Control single or all of the devices',
    'tipServo':'Activate/deactivate the servos',
    'tipGyro':'Activate/deactivate the gyroscope',
    'tipRandom':'Activate/deactivate the random behaviors\n* in certain modes',
    'tipBinder':'Bind to other joints',
    'tipRevBinder':'Reversely bind to other joints',
    'tipPlay':'Go through the sheduler from the active frame\nYou may stop while playing',
    'tipImport':'Import skills from files or texts',
    'tipRestart':'Clear all the frames in the scheduler!',
    'tipExport':'The skill will be sent in real time and saved\nin the static memory of the robot\nUse serial token \'T\' to call the last sent skill',
    'tipMirror':'Mirror the current frame',
    'tipMirrorXport':'Mirror the whole skill when exporting\n* Effective when exporting the whole skill',
    'tipGorB':'A behavior interpolates between the key frames and excutes only once\nA gait loops over all the frames without any smoothing',
    'tipLoop':'Set the starting and ending frames for looping\n* Effective when exporting the whole skill',
    'tipRepeat':'Enter the number of loops\n* Effective when exporting the whole skill',
    'tipSet':'Jump to/save the current frame',
    'tipStep':'Unit: degree/step\n* Effective when exporting the whole skill',
    'tipDelay':'Unit: milisecond\n* Effective when exporting the whole skill',
    'tipTrig':'Trigger the next frame only when the body rolls\nover the triggering angle in a certain direction\n* Effective when exporting the whole skill',
    'tipTrigAngle':'The critical angle for the trigger',
    'tipNote':'Give the frame an easy to remember name',
    'tipAdd':'Copy the active frame and\ninsert it to the next row',
    'tipDel':'Delete the current frame',
    

    

}
textCN = {
    'lan':'Chinese',
    'lanOption':'中文',
    'lanMenu':'语言',
    'uiTitle':'派拓艺桌面应用',
    'skillComposerTitle':'派拓艺技能创作坊',
    'calibTitle':'关节校准器',
    'Skill Composer':'技能创作坊',
    'Task Scheduler':'任务时序器',
    'Model':'产品',
    'Utility':'应用工具',
    'Joint Calibrator':'关节校准',
    'Scheduler':'时序器',
    'Firmware Uploader':'固件上载',
    'Exit':'退出',
    'Help':'帮助',
    'About':'关于',
    'Repeat':'重复',
    'Loop':'循环',
    'Frame':'帧',
    'Step':'速度',
    'Delay':'延时',
    'Trig':'触发轴',
    'Angle':'触发角',
    'Note':'标记',
    'Del':'删除',
    'Add':'添加',
    'Set':'设置',
    'Save':'保存',
    'Stop':'停止',
    'Joint Controller':'关节控制器',
    'Unbind All':'取消所有绑定',
    'Yaw':'偏航',
    'Pitch':'俯仰',
    '-Pitch':'逆俯仰',
    'Roll':'横滚',
    '-Roll':'逆横滚',
    'Spinal':'脊向',
    'Height':'高度',
    'Sideway':'侧向',
    'Head Pan':'头部平转',
    'Head Tilt':'头部俯仰',
    'Tail Pan':'尾巴平转',
    'N/A':'闲置',
    'Left Front':'左前',
    'Right Front':'右前',
    'Right Back':'右后',
    'Left Back':'左后',
    'Shoulder':'肩',
    'Arm':'臂',
    'Knee':'膝',
    'State Dials':'状态开关',
    'Connect':'连接',
    'Connected':'已连接',
    'Listening':'检测中',
    'All':'全部',
    'None':'无',
    'Servo':'舵机',
    'Pause':'暂停',
    'Gyro':'陀螺仪',
    'Random':'随机行为',
    'Postures':'预设姿态',
    'Skill Editor':'技能编辑器',
    'Play':'播放',
    'Import':'导入',
    'Restart':'重置',
    'Export':'导出',
    'Undo':'撤消',
    'Redo':'重复',
    'Open File':'打开文件',
    'Cancel':'取消',
    'Ok':'确认',
    'exampleFormat':'从文件导入，或以下列格式从 instinct.h 复制粘贴技能数组。\n* 保留大括号!',
    'Quit':'退出',
    'Do you want to quit?':'要退出吗?',
    'mirror':'      镜像导出',
    '>|<':'>|<',
    'Gait':'   步态',
    'Behavior':'   行为',
    'Clear':'清空',
    'max':'最快',
    'Calibration':'校准位',
    'Stand Up':'站立',
    'Rest':'休息',
    'Abort':'放弃',
    'Do you want to save the offsets?':'要保存校准值吗？',

    'uploaderTitle': '上传工具',
    'labTrans': '切换语言',
    'title': '上传工具',
    'labTrans': '切换语言',
    'labChi': '中文',
    'labEng': '英文',
    'labHelp': '帮助',
    'labAbout': '关于',
    'labExit': '退出',
    'labFileDir': '选择release文件夹',
#    'btnFileDir': '...',
    'titleFileDir': '请选择release文件夹',
    'labPort': '串口',
    'labSoftwareVersion': '软件版本',
    'labBoardVersion': '主板型号',
    'labProduct': '产品',
    'labMode': '模式',
    'btnUpload': '上传',
    'titleWarning': "警告",
    'msgFileDir': '请选择release文件夹!',
    'msgPort': '请选择正确的串口!',
    'Uploading': '上传',
    'is successully uploaded':' 上传成功！',
    'failed to upload':' 上传失败！',
    'titleVersion': '版本信息',
    'msgVersion': '''版本：1.0.0
    OpenCat固件上传工具
    版权所有 © 2018-2022
    派拓艺（深圳）科技有限责任公司
    https://www.petoi.com\n
    ''',
    'reset joints?': '舵机校准参数清零? (Y/N)',
    'reseting joints': '校准参数清零中...',
    'joints reset': '校准参数清零完成！',
    
    'update instincts?':'更新技能? (Y/N)',
    'updating instincts':'刷新EEPROM数据......',
    'instincts updated': '更新技能完成!',
    
    'calibrate IMU?':'''校准 IMU? (Y/N)
            注意: 请务必将 Bittle / Nybble 保持水平放置!''' ,
    'calibrating IMU': 'IMU校准中...',
    'IMU calibrated': 'IMU校准完成！',
            
            
    'parameterFinish': '参数初始化完成！',
    'msgFinish': '固件上传完成!',
    'msgMode': '无效模式，请选择其他模式!',
    'Standard':'标准',
    'Random_Mind':'随机',
    'Ultrasonic':'超声波',
    'Voice':'语音',
    'Camera':'摄像头',
    'Parameters':'参数',
    'Main function':'主程序',
    
    'tipConnect':'持续更新活跃串口列表直到被挂起',
    'tipPortMenu':'控制单个或所有设备',
    'tipServo':'启用或禁用舵机',
    'tipGyro':'启用或禁用陀螺仪',
    'tipRandom':'启用或禁用随机动作\n* 只在某些模式下',
    'tipBinder':'绑定其他关节',
    'tipRevBinder':'反绑其他关节',
    'tipPlay':'从当前帧开始播放时序器中的动作\n可以中途停止',
    'tipImport':'从文件或文本导入技能',
    'tipRestart':'清空时序器中的所有帧！',
    'tipExport':'技能会实时发送并保存在机器人的静态内存\n可以通过串口指令\'T\'调用上次发送的技能',
    'tipMirror':'镜像当前帧',
    'tipMirrorXport':'导出整个技能的镜像\n* 在导出整体技能时生效',
    'tipGorB':'行为给关键帧插值并只执行一轮\n步态循环执行所有帧并且不加平滑处理',
    'tipLoop':'选择循环的起止帧\n* 在导出整体技能时生效',
    'tipRepeat':'输入循环次数\n* 在导出整体技能时生效',
    'tipSet':'跳入/保存当前帧',
    'tipStep':'单位：度/步长\n* 在导出整体技能时生效',
    'tipDelay':'单位：毫秒\n* 在导出整体技能时生效',
    'tipTrig':'当机身以特定方向越过触发角时触发下一帧\n* 在导出整体技能时生效',
    'tipTrigAngle':'触发临界角',
    'tipNote':'给当前帧起一个便于记忆的名字',
    'tipAdd':'复制当前帧并插入到下一行',
    'tipDel':'删除当前帧',
}

textFR={
    'lan':'French',
    'lanOption':'Français',
    'lanMenu':'Langue',
    'Model':'Maquette',
    'Exit':'Sortie',
    'Help':'Aider',
    #to be finished
}
textJP={
    'lan':'Japanese',
    'lanOption':'日语',
    'lanMenu':'语言',
    'Model':'モデル',
    'Exit':'出口',
    'Help':'ヘルプ',
    #to be finished
}

textIT = {
    'lan':'Italiano Italian',
    'lanOption':'Italian',
    'lanMenu':'Lingua',
    'skillComposerTitle':'Petoi compositore per OpenCat',
    'Model':'Modello',
    'Scheduler':'Sequenza',
    'Exit':'Uscita',
    'Help':'Aiuto',
    'About':'Chi siamo',
    'Repeat':'Ripeti',
    'Loop':'Loop',
    'Frame':'Quadro',
    'Speed':'Velocita',
    'Delay/ms':'Ritardo',
    'Trig':'Trig',
    'Angle':'Angolo',
    'Note':'Nota',
    'Del':'Canc',
    'Add':'Aggingi',
    'Set':'Set',
    'Save':'Salva',
    'Stop':'Stop',
    'Joint Controller':'Controllo multiplo',
    'Yaw':'Yaw',
    'Pitch':'Pitch',
    '-Pitch':'-Pitch',
    'Roll':'Roll',
    '-Roll':'-Roll',
    'Spinal':'Spinal',
    'Head Pan':'Rotazione testa',
    'Head Tilt':'Inclinazione testa',
    'Tail Pan':'Scodinzolo',
    'N/A':'N/A',
    'Left Front':'Sinistra Frontale',
    'Right Front':'Destra Frontale',
    'Right Back':'Destra Posteriore',
    'Left Back':'Sinistra Posteriore',
    'Shoulder':'Spalla',
    'Arm':'Arto superiore',
    'Knee':'Arto Inferiore',
    'State Dials':'Selezioni connessioni',
    'Connect':'Connetti',
    'Connected':'Connesso',
    'Listening':'In ascolto',
    'All':'Tutti',
    'None':'Nessuno',
    'Servo':'Servo',
    'Gyro':'Gyro',
    'Random':'Random',
    'tipConnect':'Keep updating the active serial\nports until it\'s disabled',
    'tipPortMenu':'Controlla dispositivon singolo o tutti',
    'tipServo':'Attiva/Disattiva servos',
    'tipGyro':'Attiva/Disattiva giroscopio',
    'tipRandom':'Attiva/Disattiva comportamento random\n* in alcune modalita ',
    
    'Pause':'Pausa',
    'Gyro':'Gyro',
    'Random':'Random',
    'Postures':'Posizioni Preset',
    'Skill Editor':'Skill Editor',
    'Play':'Start',
    'Import':'Importa',
    'Restart':'Restart',
    'Export':'Esporta',
    'Undo':'Undo',
    'Redo':'Redo',
    'Open File':'Apri File',
    'Cancel':'Cancella',
    'Ok':'Ok',
    'exampleFormat':'Importa skill data da instinct.h nel seguente formato:',
    'Disconnect':'Disconnetti',
    'Connect':'Connetti',
    'Pause':'Pausa',
    'Paused':'In pausa',
    'Gyro:OFF':'Gyro:OFF',
    'Gyro: ON':'Gyro: ON',
    'Random:OFF':'Random:OFF',
    'Random: ON':'Random: ON',
    'Quit':'Esci',
    'Do you want to quit?':'Vuoi uscire ?',
    'Mirror':'Specchio',
    'Gait':'Cammina',
    'Behavior':'Comportamento',
    'Clear':'Cancella',
}

languageList = {
    'English':textEN,
    'Chinese':textCN,
    'Italian':textIT,
    'French':textFR,
    'Japanese':textJP,
    #to be added
}
