versionNum = '1.0.2'
dateStr = '2023-03-08'

textEN = {
    'lan':'English',
    'lanOption':'English',
    'lanMenu':'Language',
    'uiTitle':'Petoi Desktop App',
    'calibTitle':'Joint Calibrator',
    'skillComposerTitle':'Petoi Skill Composer for OpenCat',
    'Model':'Model',
    'Utility':'Utility',
    'Joint Calibrator':'Joint Calibrator',
    'Skill Composer':'Skill Composer',
    'Task Scheduler':'Task Scheduler',
    'Scheduler':'Scheduler',
    'Firmware Uploader':'Firmware Uploader',
    'Eye color picker':'Eye color picker',
    'Exit':'Exit',
    'Help':'Help',
    'About':'About',
    'Repeat':'Repeat',
    'Loop':'Loop',
    'Frame':'Frame',
    'Step':'Step',
    'Delay':'Delay',
    'Trig':'Trigger',
    'Angle':'Angle',
    'Note':'Note',
    'Del':'Del',
    'Add':'Add',
    'Set':'Set',
    'Save':'Save',
    'Stop':'Stop',
    'Joint Controller':'Joint Controller',
    'Unbind All':'Unbind All',
    'Yaw':'Yaw',
    'Pitch':'Pitch',
    '-Pitch':'-Pitch',
    'Roll':'Roll',
    '-Roll':'-Roll',
    'Spinal':'Spinal',
    'Height':'Height',
    'Sideway':'Sideway',
    'Head Pan':'Head Pan',
    'Head Tilt':'Head Tilt',
    'Tail Pan':'Tail Pan',
    'N/A':'N/A',
    'Left Front':'Left Front',
    'Right Front':'Right Front',
    'Right Back':'Right Back',
    'Left Back':'Left Back',
    'Shoulder':'Shoulder',
    'Arm':'Arm',
    'Knee':'Knee',
    'State Dials':'State Dials',
    'Connect':'Connect',
    'Connected':'Connected',
    'Listening':'Listening',
    'All':'All',
    'None':'None',
    'Servo':'Servo',
    'Gyro':'Gyro',
    'Random':'Random',
    'Send':'Send',
    'Postures':'Preset Postures',
    'Skill Editor':'Skill Editor',
    'Play':'Play',
    'Pause':'Pause',
    'Import':'Import',
    'Restart':'Restart',
    'Export':'Export',
    'Undo':'Undo',
    'Redo':'Redo',
    'Open File':'Open File',
    'Cancel':'Cancel',
    'OK':'OK',
    'Refresh':'Refresh',
    'Multiple':'Multiple',
    'Skill List':'Skill List',
    'Type of skill':'Type of skill',
    'Name of skill':'Name of skill',
    'exampleFormat':'Import from files, or copy & paste the skill data from instinct.h in the following format.\n* Keep the curly brackets!',
    'Quit':'Quit',
    'Do you want to quit?':'Do you want to quit?',
    'mirror':'      MirrorAll',
    '>|<':'>|<',
    'Posture': '  Posture',
    'Gait':'  Gait',
    'Behavior':'  Behavior',
    'Clear':'Clear',
    'max':'max',
    'Manual mode':'Manual mode',
    'Please disconnect and reconnect the device from the computer side': 'Please disconnect and\nreconnect the device\nfrom the COMPUTER side!',
    'Calibrate':'Calibrate',
    'Rest':'Rest',
    'Stand Up':'Stand Up',
    'Walk':'Walk',
    'Abort':'Abort',
    'Do you want to save the offsets?':'Do you want to save the offsets?',
    'uploaderTitle': 'Firmware Uploader',
    'labTrans': 'Change Language',
    'labChi': 'Chinese',
    'labEng': 'English',
    'labHelp': 'Help',
    'labAbout': 'About',
    'labExit': 'Exit',
    'labFileDir': 'Choose the release folder',
    'btnFileDir': '...',
    'titleFileDir': 'Please choose the release folder',
    'labPort': 'Serial port',
    'labSoftwareVersion': 'Software version',
    'labBoardVersion': 'Board version',
    'labProduct': 'Product',
    'labMode': 'Mode',
    'rbnWalk': 'Walk',
    'rbnUltrasonic': 'Ultrasonic',
    'rbnCamera': 'Camera',
    'Parameters':'Parameters',
    'Main function':'Main function',
    'btnUpload': 'Upload',
    'titleWarning': 'Warning',
    'Uploading': 'Uploading ',
    'is successully uploaded':' is successully uploaded',
    'failed to upload':' failed to upload',
    'Need to manually select the model type (Nybble/Bittle)':'Need to manually select the model type (Nybble/Bittle)',
    'msgFileDir': 'Please choose the release folder!',
    'msgPort': 'Please choose the correct serial port!',

    'msgNoneAvrdude': '''There is no avrdude. Please install avrdude at first! For details, please refer to :
    https://docs.petoi.com/desktop-app/firmware-uploader#install-avrdude-in-the-linux-os''',

    'titleVersion': 'Version information',

    'msgVersion': 'Version: ' + versionNum + '\n'+
    '''Firmware upload tool for OpenCat
    Copyright © 2018-2023
    All rights reserved Petoi LLC
    https://www.petoi.com\n''' + dateStr,

    'reset joints?': 'Reset joint offsets? (Y/N)',
    'reseting joints': 'Reset joint offsets...',
    'joints reset': 'Reset joint offsets complete!',
    
    'update instincts?':'Update Instinct? (Y/N)',
    'updating instincts':'Updating Instincts......',
    'instincts updated': 'Instincts updated',
    
    'calibrate IMU?':'''Calibrate IMU? (Y/N)
    Note: Lay the mainboard FLAT on a table!''',
    'calibrating IMU': 'Calibrating IMU...',
    'IMU calibrated': 'Calibrate IMU complete!',
    
    'parameterFinish': '''Parameters initialized!
     The next step is uploading the Main Function!''',
    'msgFinish': 'Firmware upload complete!',
    'msgMode': 'Invalide, please select another mode!',


    'Standard':'Standard',
    'RandomMind':'RandomMind',
    'Ultrasonic':'Ultrasonic',
    'Voice':'Voice',
    'Camera':'Camera',
    'RandomMind_Ultrasonic':'RandomMind_Ultrasonic',
    
    'Breath':'Breath',
    'Rotate':'Rotate',
    'Flash':'Flash',
    'Meow':'Meow',
 
    'labEdit':'Edit',
    'labTheme':'Theme',
#    '':'',
    'tipConnect':'Keep updating the active serial\nports until it\'s disabled',
    'tipPortMenu':'Control single or all of the devices',
    'tipServo':'Activate/deactivate the servos',
    'tipGyro':'Activate/deactivate the gyroscope',
    'tipRandom':'Activate/deactivate the random behaviors\n* in certain modes',
    'tipBinder':'Bind to other joints',
    'tipRevBinder':'Reversely bind to other joints',
    'tipPlay':'Go through the sheduler from the active frame\nYou may stop while playing',
    'tipImport':'Import skills from files or texts',
    'tipRestart':'Clear all the frames in the scheduler!',
    'tipExport':'The skill will be sent in real time and saved\nin the static memory of the robot\nUse serial token \'T\' to call the last sent skill',
    'tipMirror':'Mirror the current frame',
    'tipMirrorXport':'Mirror the whole skill when exporting\n* Effective when exporting the whole skill',
    'tipGorB':'A behavior interpolates between the key frames and excutes only once\nA gait loops over all the frames without any smoothing',
    'tipLoop':'Set the starting and ending frames for looping\n* Effective when exporting the whole skill',
    'tipRepeat':'Enter the number of loops\n-1 for inifinite loop. Only the \"reset\" button can break the loop!\n* Effective when exporting the whole skill',
    'tipSet':'Jump to/save the current frame',
    'tipStep':'Unit: degree/step\n* Effective when exporting the whole skill',
    'tipDelay':'Unit: milisecond\nDelay after the current frame, before entering the next frame\nIf the trigger is valid, the delay starts after the trigger\n* Effective when exporting the whole skill',
    'tipTrig':'Trigger the next frame only when the body rolls\nover the triggering angle in a certain direction\n* Effective when exporting the whole skill',
    'tipTrigAngle':'The critical angle for the trigger\n* Effective when exporting the whole skill',
    'tipNote':'Give the frame an easy to remember name',
    'tipAdd':'Copy the active frame and\ninsert it to the next row',
    'tipDel':'Delete the current frame',
    
    'tipImgWiring':'Pay attention to the location and direction of the servo plugs\nLong-press the battery\'s button to turn on the power\nClick \"Calibrate\" to rotate all the servos to the calibration state\nAttach the legs and head perpendicularly\nUse the slider to align the edges of the legs and the reference ruler parallelly',
    'tipImgPosture':'Switch between postures to test the calibration results\nSave the offsets in time\nNo need for calibration in the future',
}
textCN = {
    'lan':'Simplified Chinese',
    'lanOption':'中文',
    'lanMenu':'语言',
    'uiTitle':'派拓艺桌面应用',
    'skillComposerTitle':'派拓艺技能创作坊',
    'calibTitle':'关节校准器',
    'Skill Composer':'技能创作坊',
    'Task Scheduler':'任务时序器',
    'Model':'产品',
    'Utility':'应用工具',
    'Joint Calibrator':'关节校准',
    'Scheduler':'时序器',
    'Firmware Uploader':'固件上载',
    'Eye color picker':'眼色选择器',
    'Exit':'退出',
    'Help':'帮助',
    'About':'关于',
    'Repeat':'重复',
    'Loop':'循环',
    'Frame':'帧',
    'Step':'速度',
    'Delay':'延时',
    'Trig':'触发轴',
    'Angle':'触发角',
    'Note':'标记',
    'Del':'删除',
    'Add':'添加',
    'Set':'设置',
    'Save':'保存',
    'Stop':'停止',
    'Joint Controller':'关节控制器',
    'Unbind All':'取消所有联动',
    'Yaw':'偏航',
    'Pitch':'俯仰',
    '-Pitch':'逆俯仰',
    'Roll':'横滚',
    '-Roll':'逆横滚',
    'Spinal':'脊向',
    'Height':'高度',
    'Sideway':'侧向',
    'Head Pan':'头部平转',
    'Head Tilt':'头部俯仰',
    'Tail Pan':'尾巴平转',
    'N/A':'闲置',
    'Left Front':'左前',
    'Right Front':'右前',
    'Right Back':'右后',
    'Left Back':'左后',
    'Shoulder':'肩',
    'Arm':'臂',
    'Knee':'膝',
    'State Dials':'状态开关',
    'Connect':'连接',
    'Connected':'已连接',
    'Listening':'检测中',
    'All':'全部',
    'None':'无',
    'Servo':'舵机',
    'Pause':'暂停',
    'Gyro':'陀螺仪',
    'Random':'随机行为',
    'Send':'发送',
    'Postures':'预设姿态',
    'Skill Editor':'技能编辑器',
    'Play':'播放',
    'Import':'导入',
    'Restart':'重置',
    'Export':'导出',
    'Undo':'撤消',
    'Redo':'重复',
    'Open File':'打开文件',
    'Cancel':'取消',
    'OK':'确认',
    'Multiple':'载入多个',
    'Skill List':'技能表',
    'Type of skill':'技能类型',
    'Name of skill':'技能名',
    'exampleFormat':'从文件导入，或以下列格式从 instinct.h 复制粘贴技能数组。\n* 保留大括号!',
    'Quit':'退出',
    'Do you want to quit?':'要退出吗?',
    'mirror':'      镜像导出',
    '>|<':'>|<',
    'Posture': '   姿势',
    'Gait':'   步态',
    'Behavior':'   行为',
    'Clear':'清空',
    'max':'最快',
    'Calibrate':'校准位',
    'Rest':'休息',
    'Stand Up':'站立',
    'Walk':'行走',
    'Abort':'放弃',
    "Refresh":"刷新",
    'Manual mode':"手动模式",
    'Do you want to save the offsets?':'要保存校准值吗？',
    'Need to manually select the model type (Nybble/Bittle)':'请手动选择型号(Nybble/Bittle)',
    'uploaderTitle': '上传工具',
    'labTrans': '切换语言',
    'title': '上传工具',
    'labTrans': '切换语言',
    'labChi': '中文',
    'labEng': '英文',
    'labHelp': '帮助',
    'labAbout': '关于',
    'labExit': '退出',
    'labFileDir': '选择release文件夹',
#    'btnFileDir': '...',
    'titleFileDir': '请选择release文件夹',
    'labPort': '串口',
    'labSoftwareVersion': '软件版本',
    'labBoardVersion': '主板型号',
    'labProduct': '产品',
    'labMode': '模式',
    'btnUpload': '上传',
    'titleWarning': "警告",
    'msgFileDir': '请选择release文件夹!',
    'msgPort': '请选择正确的串口!',

    'msgNoneAvrdude': '''没有找到可执行程序文件 avrdude。请先安装 avrdude！详细说明请参考：
    https://docs.petoi.com/v/chinese/zhuo-mian-ying-yong/gu-jian-shang-zai#linux-xi-tong-zhong-an-zhuang-avrdude''',

    'Uploading': '上传',
    'is successully uploaded':' 上传成功！',
    'failed to upload':' 上传失败！',
    'titleVersion': '版本信息',

    'msgVersion': '版本：' + versionNum + '\n'+
    '''OpenCat固件上传工具
    版权所有 © 2018-2023
    派拓艺（深圳）科技有限责任公司
    https://www.petoi.com\n''' + dateStr,

    'reset joints?': '舵机校准参数清零? (Y/N)',
    'reseting joints': '校准参数清零中...',
    'joints reset': '校准参数清零完成！',
    
    'update instincts?':'更新技能? (Y/N)',
    'updating instincts':'刷新EEPROM数据......',
    'instincts updated': '更新技能完成!',
    
    'calibrate IMU?':'''校准 IMU? (Y/N)
            注意: 请务必将主板保持水平放置!''' ,
    'calibrating IMU': 'IMU校准中...',
    'IMU calibrated': 'IMU校准完成！',
            
            
    'parameterFinish': '''参数初始化完成！
                       接下来将开始上传主程序!''',
    'msgFinish': '固件上传完成!',
    'msgMode': '无效模式，请选择其他模式!',
    'Standard':'标准',
    'RandomMind':'随机',
    'Ultrasonic':'超声波',
    'Voice':'语音',
    'Camera':'摄像头',
    'RandomMind_Ultrasonic':'随机_超声波',
    'Parameters':'参数',
    'Main function':'主程序',
    
    'Breath':'渐变',
    'Rotate':'旋转',
    'Flash':'闪烁',
    'Meow':'喵！',
    'Please disconnect and reconnect the device from the computer side':'请在电脑端断开设备再重新连接!',
    'labEdit':'编辑',
    'labTheme':'主题',
    'tipConnect':'持续更新活跃串口列表直到被挂起',
    'tipPortMenu':'控制单个或所有设备',
    'tipServo':'启用或禁用舵机',
    'tipGyro':'启用或禁用陀螺仪',
    'tipRandom':'启用或禁用随机动作\n* 只在某些模式下',
    'tipBinder':'正向联动其他关节',
    'tipRevBinder':'反向联动其他关节',
    'tipPlay':'从当前帧开始播放时序器中的动作\n可以中途停止',
    'tipImport':'从文件或文本导入技能',
    'tipRestart':'清空时序器中的所有帧！',
    'tipExport':'技能会实时发送并保存在机器人的静态内存\n可以通过串口指令\'T\'调用上次发送的技能',
    'tipMirror':'镜像当前帧',
    'tipMirrorXport':'导出整个技能的镜像\n* 在导出整体技能时生效',
    'tipGorB':'行为给关键帧插值并只执行一轮\n步态循环执行所有帧并且不加平滑处理',
    'tipLoop':'选择循环的起止帧\n* 在导出整体技能时生效',
    'tipRepeat':'输入循环次数\n-1为无限循环，只有按复位键才能跳出循环!\n* 在导出整体技能时生效',
    'tipSet':'跳入/保存当前帧',
    'tipStep':'单位：度/步长\n* 在导出整体技能时生效',
    'tipDelay':'单位：毫秒\n完成当前帧后延时，再执行下一帧\n如触发器有效，则在触发后才开始延时\n* 在导出整体技能时生效',
    'tipTrig':'当机身以特定方向越过触发角时触发下一帧\n* 在导出整体技能时生效',
    'tipTrigAngle':'触发临界角\n* 在导出整体技能时生效',
    'tipNote':'给当前帧起一个便于记忆的名字',
    'tipAdd':'复制当前帧并插入到下一行',
    'tipDel':'删除当前帧',
    'tipImgWiring':'接舵机线时注意插头的位置和正反\n长按电池按钮通电\n点击“校准“使所有舵机旋转到校准位\n按垂直关系安装四肢和头\n控制滑条使大小腿边缘与校准尺平行',
    'tipImgPosture':'在各姿势间切换，检查校准效果\n及时保存修正值\n后续使用无需再校准',
}

textCN_TW = {
    'lan':'Traditional Chinese',
    'lanOption':'繁体中文',
    'lanMenu':'語言',
    'uiTitle':'Petoi桌面應用',
    'skillComposerTitle':'Petoi技能創作坊',
    'calibTitle':'關節校準器',
    'Skill Composer':'技能創作坊',
    'Task Scheduler':'任務排程器',
    'Model':'產品',
    'Utility':'應用工具',
    'Joint Calibrator':'關節校準',
    'Scheduler':'排程器',
    'Firmware Uploader':'固件上傳',
    'Eye color picker':'眼睛顏色選擇器',
    'Exit':'退出',
    'Help':'幫助',
    'About':'關於',
    'Repeat':'重複',
    'Loop':'循環',
    'Frame':'幀',
    'Step':'速度',
    'Delay':'延遲',
    'Trig':'觸發',
    'Angle':'角度',
    'Note':'標記',
    'Del':'刪除',
    'Add':'添加',
    'Set':'設置',
    'Save':'儲存',
    'Stop':'停止',
    'Joint Controller':'關節控制器',
    'Unbind All':'取消所有聯動',
    'Yaw':'偏航',
    'Pitch':'俯仰',
    '-Pitch':'逆俯仰',
    'Roll':'横滾動',
    '-Roll':'逆横滾動',
    'Spinal':'脊向',
    'Height':'高度',
    'Sideway':'側向',
    'Head Pan':'頭部平轉',
    'Head Tilt':'頭部俯仰',
    'Tail Pan':'尾巴平轉',
    'N/A':'閒置',
    'Left Front':'左前',
    'Right Front':'右前',
    'Right Back':'右後',
    'Left Back':'左後',
    'Shoulder':'肩',
    'Arm':'臂',
    'Knee':'膝',
    'State Dials':'狀態開關',
    'Connect':'連接',
    'Connected':'已連接',
    'Listening':'檢測中',
    'All':'全部',
    'None':'無',
    'Servo':'伺服',
    'Pause':'暫停',
    'Gyro':'陀螺儀',
    'Random':'随機行為',
    'Send':'發送',
    'Postures':'預設姿態',
    'Skill Editor':'技能编輯器',
    'Play':'播放',
    'Import':'導入',
    'Restart':'重置',
    'Export':'導出',
    'Undo':'撤消',
    'Redo':'重複',
    'Open File':'打開文件',
    'Cancel':'取消',
    'OK':'確認',
    'Multiple':'載入多個',
    'Skill List':'技能表',
    'Type of skill':'技能類型',
    'Name of skill':'技能名',
    'exampleFormat':'從文件導入，或以下列格式從 instinct.h 複製黏貼技能數組。\n* 保留大括號!',
    'Quit':'退出',
    'Do you want to quit?':'要退出嗎?',
    'mirror':'      鏡像導出',
    '>|<':'>|<',
    'Posture': '   姿勢',
    'Gait':'   步態',
    'Behavior':'   行為',
    'Clear':'清空',
    'max':'最快',
    'Calibrate':'校準位',
    'Rest':'休息',
    'Stand Up':'站立',
    'Walk':'行走',
    'Abort':'放棄',
    'Refresh':'刷新',
    'Manual mode':'手動模式',
    'Do you want to save the offsets?':'要保存校準值嗎？',
    'Need to manually select the model type (Nybble/Bittle)':'請手動選擇型號(Nybble/Bittle)',
    'uploaderTitle': '上傳者標題',
    'labTrans': '切換語言',
    'title': '標題',
    'labTrans': '切換語言',
    'labChi': '中文',
    'labEng': '英文',
    'labHelp': '幫助',
    'labAbout': '關於',
    'labExit': '退出',
    'labFileDir': '選擇release文件夾',
#    'btnFileDir': '...',
    'titleFileDir': '請選擇release文件夾',
    'labPort': '端口',
    'labSoftwareVersion': '軟件版本',
    'labBoardVersion': '主板型號',
    'labProduct': '產品',
    'labMode': '模式',
    'btnUpload': '上傳',
    'titleWarning': '警告',
    'msgFileDir': '請選擇release文件夾!',
    'msgPort': '請選擇正確的端口!',

    'msgNoneAvrdude': '''沒有找到可執行程式文件 avrdude。請先安裝 avrdude！詳細說明請參考：
    https://docs.petoi.com/v/chinese/zhuo-mian-ying-yong/gu-jian-shang-zai#linux-xi-tong-zhong-an-zhuang-avrdude''',

    'Uploading': '上傳',
    'is successully uploaded':' 上傳成功！',
    'failed to upload':' 上傳失敗！',
    'titleVersion': '版本信息',

    'msgVersion': '版本：' + versionNum + '\n'+
    '''OpenCat固件上傳工具
    版權所有 © 2018-2023
    派拓藝（深圳）科技有限责任公司
    https://www.petoi.com\n''' + dateStr,

    'reset joints?': '舵機校準參數清零? (Y/N)',
    'reseting joints': '校準參數清零中...',
    'joints reset': '校準參數清零完成！',
    
    'update instincts?':'更新技能? (Y/N)',
    'updating instincts':'刷新EEPROM數據......',
    'instincts updated': '更新技能完成!',
    
    'calibrate IMU?':'''校準 IMU? (Y/N)
            注意: 請務必將主板保持水平放置!''' ,
    'calibrating IMU': 'IMU校準中...',
    'IMU calibrated': 'IMU校準完成！',
            
            
    'parameterFinish': '''參數初始化完成！
                       接下來將開始上傳主程序!''',
    'msgFinish': '固件上傳完成!',
    'msgMode': '無效模式，請選擇其他模式!',
    'Standard':'標準',
    'RandomMind':'随機',
    'Ultrasonic':'超聲波',
    'Voice':'語音',
    'Camera':'鏡頭',
    'RandomMind_Ultrasonic':'随機_超聲波',
    'Parameters':'參數',
    'Main function':'主程序',
    
    'Breath':'漸變',
    'Rotate':'旋轉',
    'Flash':'閃爍',
    'Meow':'喵！',
    'Please disconnect and reconnect the device from the computer side':'請在電腦端斷開設備再重新連接!',
    
    'labEdit':'编辑',
    'labTheme':'主题',
    'tipConnect':'持續更新活耀端口列表直到被掛起',
    'tipPortMenu':'控制單個或所有設備',
    'tipServo':'啟用或禁用舵機',
    'tipGyro':'啟用或禁用陀螺儀',
    'tipRandom':'啟用或禁用随機動作\n* 只在某些模式下',
    'tipBinder':'正向聯動其他關節',
    'tipRevBinder':'反向聯動其他關節',
    'tipPlay':'從當前幀開始播放時序器中的動作\n可以中途停止',
    'tipImport':'從文件或文本導入技能',
    'tipRestart':'清空时序器中的所有幀！',
    'tipExport':'技能會實時發送並保存在機器人的静態内存\n可以通過端口指令\'T\'適用上次發送的技能',
    'tipMirror':'鏡像當前幀',
    'tipMirrorXport':'導出整個技能的鏡像\n* 在導出整體技能時生效',
    'tipGorB':'行為給關鍵幀插值並只執行一輪\n步態循環執行所有幀並且不加平滑處理',
    'tipLoop':'選擇循環的起止幀\n* 在導出整體技能時生效',
    'tipRepeat':'輸入循環次數\n-1為無限循環，只有按復位健才能跳出循環!\n* 在導出整體技能時生效',
    'tipSet':'跳入/保存當前幀',
    'tipStep':'單位：度/步長\n* 在導出整體技能時生效',
    'tipDelay':'單位：毫秒\n完成當前幀後延時，再執行下一幀\n如觸發器有效，則在觸發後才開始延時\n* 在導出整體技能時生效',
    'tipTrig':'當機身以特定方向越過觸發角時觸發下一幀\n* 在導出整體技能時生效',
    'tipTrigAngle':'觸發臨界角\n* 在導出整體技能時生效',
    'tipNote':'给當前幀起一個便於記憶的名字',
    'tipAdd':'複製當前幀並插入到下一行',
    'tipDel':'刪除當前幀',
    'tipImgWiring':'接舵機線时注意插頭的位置和正反\n長按電池按鈕通電\n點擊“校準“使所有舵機旋轉到校準位\n按垂直關係安装四肢和頭\n控制滑條使大小腿邊緣與校準尺平行',
    'tipImgPosture':'在各姿勢間切换，檢查校準效果\n及時保存修正值\n後續使用無需再校準',
}


textDE = {
'lan':'German',
'lanOption':'Deutsh',
'lanMenu':'Sprache',
'uiTitle':'Petoi Desktop-App',
'calibTitle':'Gelenkkalibrator',
'skillComposerTitle':'Petoi Einstellungen Fähigkeiten für OpenCat',
'Model':'Modell',
'Utility':'Werkzeug',
'Joint Calibrator':'Gelenkkalibrator',
'Skill Composer':'Einstellungen Fähigkeiten',
'Task Scheduler':'Aufgabenplaner',
'Scheduler':'Planer',
'Firmware Uploader':'Firmware-Uploader',
'Eye color picker':'Augenfarbauswahl',
'Exit':'Beenden',
'Help':'Hilfe',
'About':'Über',
'Repeat':'Wiederholen',
'Loop':'Schleife',
'Frame':'Frame',
'Step':'Schritt',
'Delay':'Verzögerung',
'Trig':'Auslöser',
'Angle':'Winkel',
'Note':'Notiz',
'Del':'Löschen',
'Add':'Hinzufügen',
'Set':'Einstellen',
'Save':'Speichern',
'Stop':'Stoppen',
'Joint Controller':'Gelenk-Controller',
'Unbind All':'Alle lösen',
'Yaw':'Gier',
'Pitch':'Nick',
'-Pitch':'-Nick',
'Roll':'Roll',
'-Roll':'-Roll',
'Spinal':'Wirbelsäule',
'Height':'Höhe',
'Sideway':'Seitwärts',
'Head Pan':'Kopf-Pan',
'Head Tilt':'Kopf-Neigung',
'Tail Pan':'Schwanz-Pan',
'N/A':'N/V',
'Left Front':'Links vorne',
'Right Front':'Rechts vorne',
'Right Back':'Rechts hinten',
'Left Back':'Links hinten',
'Shoulder':'Schulter',
'Arm':'Arm',
'Knee':'Knie',
'State Dials':'Zustandsregler',
'Connect':'Verbinden',
'Connected':'Verbunden',
'Listening':'Hören',
'All':'Alle',
'None':'Keine',
'Servo':'Servo',
'Gyro':'Gyro',
'Random':'Zufällig',
'Send':'Schicken',
'Postures':'Voreingestellte Haltungen',
'Skill Editor':'Skill-Editor',
'Play':'Abspielen',
'Pause':'Pausieren',
'Import':'Importieren',
'Restart':'Neustart',
'Export':'Exportieren',
'Undo':'Rückgängig',
'Redo':'Wiederholen',
'Open File':'Datei öffnen',
'Cancel':'Abbrechen',
'OK':'OK',
'Refresh':'Aktualisieren',
'Multiple':'Mehrere',
'Skill List':'Skill-Liste',
'Type of skill':'Art des Skills',
'Name of skill':'Name des Skills',
'exampleFormat':'Importiere aus Dateien oder kopiere die Skill-Daten von instinct.h im folgenden Format.\n* Behalte die geschweiften Klammern bei!',
'Quit':'Beenden',
'Do you want to quit?':'Möchten Sie beenden?',
'mirror':'Spiegeln',
'>|<':'>|<',
'Posture': '  Posture',
'Gait':'Gangart',
'Behavior':'Verhalten',
'Clear':'Löschen',
'max':'max.',
'Manual mode':'Manueller Modus',
'Please disconnect and reconnect the device from the computer side': 'Bitte trennen und\nwieder anschließen\nder Gerät von der\nCOMPUTER-Seite!',
'Calibrate':'Kalibrieren',
'Rest':'Ruhe',
'Stand Up':'Aufstehen',
'Walk':'Gehen',
'Abort':'Abbrechen',
'Do you want to save the offsets?':'Möchten Sie die Abweichungen speichern?',
'uploaderTitle': 'Firmware-Uploader',
'labTrans': 'Sprache ändern',
'labChi': 'Chinesisch',
'labEng': 'Englisch',
'labHelp': 'Hilfe',
'labAbout': 'Über',
'labExit': 'Beenden',
'labFileDir': 'Wählen Sie das Freigabe-Verzeichnis',
'btnFileDir': '...',
'titleFileDir': 'Bitte wählen Sie das Freigabe-Verzeichnis',
'labPort': 'Serielle Schnittstelle',
'labSoftwareVersion': 'Software-Version',
'labBoardVersion': 'Board-Version',
'labProduct': 'Produkt',
'labMode': 'Modus',
'rbnWalk': 'Gehen',
'rbnUltrasonic': 'Ultraschall',
'rbnCamera': 'Kamera',
'Parameters':'Parameter',
'Main function':'Hauptfunktion',
'btnUpload': 'Hochladen',
'titleWarning': 'Warnung',
'Uploading': 'Hochladen ',
'is successully uploaded':' erfolgreich hochgeladen',
'failed to upload':' konnte nicht hochgeladen werden',
'Need to manually select the model type (Nybble/Bittle)':'Sie müssen den Modelltyp manuell auswählen (Nybble/Bittle)',
'msgFileDir': 'Bitte wählen Sie das Freigabe-Verzeichnis!',
'msgPort': 'Bitte wählen Sie die korrekte serielle Schnittstelle!',

'msgNoneAvrdude': '''Es gibt kein Avrdude. Bitte installieren Sie zuerst avrdude! Einzelheiten finden Sie unter :
https://docs.petoi.com/desktop-app/firmware-uploader#install-avrdude-in-the-linux-os''',

'titleVersion': 'Versionsinformation',

'msgVersion': 'Version: ' + versionNum + '\n'+
'''Firmware-Uploader für OpenCat
Copyright © 2018-2023
Alle Rechte vorbehalten
Petoi LLC
https://www.petoi.com\n''' + dateStr,

'reset joints?': 'Gelenkabweichungen zurücksetzen? (J/N)',
'reseting joints': 'Gelenkabweichungen werden zurückgesetzt...',
'joints reset': 'Gelenkabweichungen erfolgreich zurückgesetzt!',

'update instincts?':'Instinkte aktualisieren? (J/n)',
'updating instincts':'Instinkte werden aktualisiert...',
'instincts updated': 'Instinkte aktualisiert',

'calibrate IMU?':'''IMU kalibrieren? (J/N)
Hinweis: Legen Sie das Mainboard FLACH auf einen Tisch!''',
'calibrating IMU': 'IMU wird kalibriert...',
'IMU calibrated': 'IMU erfolgreich kalibriert!',

'parameterFinish': '''Parameter initialisiert!
Der nächste Schritt ist das Hochladen der Hauptfunktion!''',
'msgFinish': 'Firmware-Hochladen abgeschlossen!',
'msgMode': 'Ungültig, bitte wählen Sie einen anderen Modus!',

'Standard':'Standard',
'RandomMind':'Zufallsmodus',
'Ultrasonic':'Ultraschall-Modus',
'Voice':'Sprachmodus',
'Camera':'Kamera',
'RandomMind_Ultrasonic':'Zufallsmodus_Ultraschall',

'Breath':'Atmen',
'Rotate':'Drehen',
'Flash':'Blitzen',
'Meow':'Miauen',

'labEdit':'Bearbeiten',
'labTheme':'Thema',
# '':'',
'tipConnect':'Aktive serielle Verbindungen aktualisieren,\nbis diese deaktiviert ist',
'tipPortMenu':'Steuerung einzelner oder aller Geräte',
'tipServo':'Servos aktivieren/deaktivieren',
'tipGyro':'Gyroskop aktivieren/deaktivieren',
'tipRandom':'Zufallsverhalten aktivieren/deaktivieren\n*',
'tipBinder':'Mit anderen Gelenken verbinden',
'tipRevBinder':'Umgekehrt mit anderen Gelenken verbinden',
'tipPlay':'Gehe durch den Ablaufplan des aktiven Frames\nDas Abspielen kann jederzeit gestoppt werden',
'tipImport':'Fähigkeiten aus Dateien oder Texten importieren',
'tipRestart':'Lösche alle Frames im Ablaufplan!',
'tipExport':'Die Fähigkeit wird in Echtzeit gesendet und\nim statischen Speicher des Roboters gespeichert\nVerwenden Sie den seriellen Token \'T\', um die zuletzt gesendete Fähigkeit aufzurufen',
'tipMirror':'Spiegeln des aktuellen Frames',
'tipMirrorXport':'Spiegeln der gesamten Fähigkeit beim Exportieren\n* Wirksam beim Exportieren der gesamten Fähigkeit',
'tipGorB':'Ein Verhalten interpoliert zwischen den Keyframes und wird nur einmal ausgeführt.\nEin Gang durchläuft alle Frames ohne Glättung.',
'tipLoop':'Setze Start- und Endframes für die Schleife\n* Wirksam beim Exportieren der gesamten Fähigkeit',
'tipRepeat':'Geben Sie die Anzahl der Schleifen ein\n-1 für unendliche Schleife. Nur die "Reset"-Taste kann die Schleife unterbrechen!\n* Wirksam beim Exportieren der gesamten Fähigkeit',
'tipSet':'Springe zu/speichere den aktuellen Frame',
'tipStep':'Einheit: Grad/Schritt\n* Wirksam beim Exportieren der gesamten Fähigkeit',
'tipDelay':'Einheit: Millisekunde\nVerzögerung nach dem aktuellen Frame, bevor der nächste Frame betreten wird.\nWenn der Auslöser gültig ist, beginnt die Verzögerung nach dem Auslöser\n* Wirksam beim Exportieren der gesamten Fähigkeit',
'tipTrig':'Trigger den nächsten Frame nur, wenn der Körper\nin eine bestimmte Richtung über den Auslösewinkel rollt\n* Wirksam beim Exportieren der gesamten Fähigkeit',
'tipTrigAngle':'Der kritische Winkel um auszulösen',
'tipNote': 'Gib dem Frame einen einfach zu merkenden Namen',
'tipAdd': 'Kopiere den aktiven Frame und\nfüge ihn in die nächste Zeile ein',
'tipDel': 'Lösche den aktuellen Frame',
'tipImgWiring': 'Achte auf den Standort und die Ausrichtung der Servostecker\nHalte die Taste des Akkus lange gedrückt, um die Stromversorgung einzuschalten\nKlicke auf "Kalibrieren", um alle Servos in den Kalibrierungsmodus zu drehen\nBefestige die Beine und den Kopf senkrecht\nVerwende den Schieberegler, um die Kanten der Beine und der Referenzskala parallel auszurichten',
'tipImgPosture': 'Wechsle zwischen Haltungen, um die Kalibrierungsergebnisse zu testen\nSpeichere die Abweichungen rechtzeitig\nKeine Notwendigkeit für zukünftige Kalibrierung',
}


textFR={
    'lan':'French',
    'lanOption':'Français',
    'lanMenu':'Langue',
    'Model':'Maquette',
    'Exit':'Sortie',
    'Help':'Aider',
    #to be finished
}
textJP={
    'lan':'Japanese',
    'lanOption':'日语',
    'lanMenu':'语言',
    'Model':'モデル',
    'Exit':'出口',
    'Help':'ヘルプ',
    #to be finished
}

textIT = {
    'lan':'Italian',
    'lanOption':'Italiano',
    'lanMenu':'Lingua',
    'uiTitle':'Applicazione desktop Petoi',
    'calibTitle':'Calibratore articolare',
    'skillComposerTitle':'Petoi compositore per OpenCat',
    'Model':'Modello',
    'Utility':'Utilità',
    'Joint Calibrator':'Calibratore articolare',
    'Skill Composer':'Compositore di abilità',
    'Task Scheduler':'Agenda',
    'Scheduler':'Sequenza',
    'Firmware Uploader':'Caricatore di firmware',
    'Eye color picker':'Selettore del colore degli occhi',
    'Exit':'Uscita',
    'Help':'Aiuto',
    'About':'Chi siamo',
    'Repeat':'Ripeti',
    'Loop':'Loop',
    'Frame':'Quadro',
    'Step':'Velocita',
    'Delay':'Ritardo',
    'Trig':'Trig',
    'Angle':'Angolo',
    'Note':'Nota',
    'Del':'Canc',
    'Add':'Aggingi',
    'Set':'Set',
    'Save':'Salva',
    'Stop':'Stop',
    'Joint Controller':'Controllo multiplo',
    'Unbind All':'Separa tutto',
    'Yaw':'Yaw',
    'Pitch':'Pitch',
    '-Pitch':'-Pitch',
    'Roll':'Roll',
    '-Roll':'-Roll',
    'Spinal':'Spinal',
    'Height':'Altezza',
    'Sideway':'Di lato',
    'Head Pan':'Rotazione testa',
    'Head Tilt':'Inclinazione testa',
    'Tail Pan':'Scodinzolo',
    'N/A':'N/A',
    'Left Front':'Sinistra Frontale',
    'Right Front':'Destra Frontale',
    'Right Back':'Destra Posteriore',
    'Left Back':'Sinistra Posteriore',
    'Shoulder':'Spalla',
    'Arm':'Arto superiore',
    'Knee':'Arto Inferiore',
    'State Dials':'Selezioni connessioni',
    'Connect':'Connetti',
    'Connected':'Connesso',
    'Listening':'In ascolto',
    'All':'Tutti',
    'None':'Nessuno',
    'Servo':'Servo',
    'Gyro':'Gyro',
    'Random':'Random',
    'Send':'Inviare',
    'Postures':'Posizioni Preset',
    'Skill Editor':'Skill Editor',
    'Play':'Start',
    'Pause':'Pausa',
    'Import':'Importa',
    'Restart':'Restart',
    'Export':'Esporta',
    'Undo':'Undo',
    'Redo':'Redo',
    'Open File':'Apri File',
    'Cancel':'Cancella',
    'OK':'OK',
    'exampleFormat':'Importa da file o copia e incolla i dati delle abilità da instinct.h nel seguente formato.\n* Mantieni le parentesi graffe!',
    'Quit':'Esci',
    'Do you want to quit?':'Vuoi uscire ?',
    'mirror':'Specchio',
    '>|<':'>|<',
    'Gait':'Cammina',
    'Behavior':'Comportamento',
    'Clear':'Cancella',
    'max':'max',
    
    'Calibrate':'Calibrate',
    'Rest':'Riposo',
    'Stand Up':'In piedi',
    'Walk':'Camminare',
    'Abort':'Interrompi',
    'Do you want to save the offsets?':'Vuoi salvare gli offset?',
    'uploaderTitle': 'Caricatore di firmware',
    'labTrans': 'Cambia lingua',
    'labChi': 'Cinese',
    'labEng': 'Inglese',
    'labHelp': 'Aiuto',
    'labAbout': 'Di',
    'labExit': 'Uscita',
    'labFileDir': 'Scegli la cartella di rilascio',
    'btnFileDir': '...',
    'titleFileDir': 'Si prega di scegliere la cartella di rilascio',
    'labPort': 'Porta seriale',
    'labSoftwareVersion': 'Versione software',
    'labBoardVersion': 'Versione da tavolo',
    'labProduct': 'Prodotto',
    'labMode': 'Modalità',
    'rbnWalk': 'Camminare',
    'rbnUltrasonic': 'Ultrasonico',
    'rbnCamera': 'Telecamera',
    'Parameters':'Parametri',
    'Main function':'Funzione principale',
    'btnUpload': 'Caricamento',
    'titleWarning': 'Avvertimento',
    'Uploading': 'Caricamento in corso ',
    'is successully uploaded':' è caricato con successo',
    'failed to upload':' impossibile caricare',

    'msgFileDir': 'Si prega di scegliere la cartella di rilascio!',
    'msgPort': 'Si prega di scegliere la porta seriale corretta!',
    'msgNoneAvrdude': '''Non c\'è avrdude. Si prega di installare avrdude all\'inizio! Per i dettagli, fare riferimento a:
    https://docs.petoi.com/desktop-app/firmware-uploader#install-avrdude-in-the-linux-os''',
    'titleVersion': 'Informazioni sulla versione',
    'msgVersion': 'Versione: ' + versionNum + '\n' +
    '''Strumento di caricamento del firmware per OpenCat
    Diritto d'autore © 2018-2022
    Tutti i diritti riservati Petoi LLC
    https://www.petoi.com\n''' + dateStr,
    'reset joints?': 'Reimpostare gli offset dei giunti? (S/N)',
    'reseting joints': 'Reimposta gli offset del giunto...',
    'joints reset': 'Ripristino offset giunti completato!',
    
    'update instincts?':'Aggiornare l\'istinto? (S/N)',
    'updating instincts':'Aggiornamento degli istinti......',
    'instincts updated': 'Istinti aggiornati',
    
    'calibrate IMU?':'''Calibrare l\'IMU? (S/N)
    Nota: Appoggia la scheda madre PIATTA su un tavolo!''',
    'calibrating IMU': 'Taratura dell\'IMU...',
    'IMU calibrated': 'Calibrazione IMU completata!',
    
    'parameterFinish': '''Parametri inizializzati!
     Il prossimo passo è caricare la funzione principale!''',
    'msgFinish': 'Caricamento del firmware completato!',
    'msgMode': 'Non valido, selezionare un\'altra modalità!',
    'Standard':'Standard',
    'RandomMind':'MenteCasuale',
    'Ultrasonic':'Ultrasonico',
    'Voice':'Voce',
    'Camera':'Telecamera',
    'RandomMind_Ultrasonic':'MenteCasuale_Ultrasonico',
    
    'Breath':'Respiro',
    'Rotate':'Ruotare',
    'Flash':'Veloce',
    'Meow':'Miao',
    'labEdit':'Modificare',
    'labTheme':'Tema',
    # '':'',
    'tipConnect':'Continua ad aggiornare le porte seriali\nattive fino a quando non viene disabilitato',
    'tipPortMenu':'Controlla dispositivon singolo o tutti',
    'tipServo':'Attiva/Disattiva servos',
    'tipGyro':'Attiva/Disattiva giroscopio',
    'tipRandom':'Attiva/Disattiva comportamento random\n* in alcune modalita',
    'tipBinder':'Legare ad altre articolazioni',
    'tipRevBinder':'Legare inversamente ad altre articolazioni',
    'tipPlay':'Passa attraverso lo sheduler dal frame attivo\nPuoi fermarti mentre giochi',
    'tipImport':'Importa competenze da file o testi',
    'tipRestart':'Cancella tutti i frame nello scheduler!',
    'tipExport':'La skill verrà inviata in tempo reale e salvata\nnella memoria statica del robot\nUsa il token seriale \'T\' per chiamare l\'ultima abilità inviata',
    'tipMirror':'Specchia il fotogramma corrente',
    'tipMirrorXport':'Rispecchia l\'intera abilità durante l\'esportazione\n* Efficace quando si esporta l\'intera abilità',
    'tipGorB':'Un comportamento esegue l\'interpolazione tra i fotogrammi chiave ed esegue una sola volta\nUn\'andatura scorre su tutti i fotogrammi senza alcuna levigatura',
    'tipLoop':'Imposta i fotogrammi iniziale e finale per il looping\n* Efficace quando si esporta l\'intera abilità',
    'tipRepeat':'Immettere il numero di loop\n-1 per loop infinito. Solo il pulsante \"reset\" può interrompere il loop!\n* Efficace quando si esporta l\'intera abilità',
    'tipSet':'Passa a/salva il fotogramma corrente',
    'tipStep':'Unità: grado/passo\n* Efficace quando si esporta l\'intera abilità',
    'tipDelay':'Unità: millisecondi\nRitardo dopo il fotogramma corrente, prima di entrare nel fotogramma successivo\nSe il trigger è valido, il ritardo inizia dopo il trigger\n* Efficace quando si esporta l\'intera abilità',
    'tipTrig':'Attiva il fotogramma successivo solo quando il corpo rotola\noltre l\'angolo di innesco in una certa direzione\n* Efficace quando si esporta l\'intera abilità',
    'tipTrigAngle':'L\'angolo critico per il grilletto\n* Efficace quando si esporta l\'intera abilità',
    'tipNote':'Dai alla cornice un nome facile da ricordare',
    'tipAdd':'Copia il frame attivo e\ninseriscilo nella riga successiva',
    'tipDel':'Elimina il fotogramma corrente',
    
    'tipImgWiring':'Prestare attenzione alla posizione e alla direzione dei connettori dei servi\nPremere a lungo il pulsante della batteria per accendere l\'alimentazione\nFare clic su \"Calibra\" per ruotare tutti i servi allo stato di calibrazione\nAttacca le gambe e la testa perpendicolarmente\nUsa il cursore per allineare parallelamente i bordi delle gambe e il righello di riferimento',
    'tipImgPosture':'Passa da una postura all\'altra per testare i risultati della calibrazione\nSalva gli offset in tempo\nNon c\'è bisogno di calibrazione in futuro',
}

languageList = {
    'English':textEN,
    'Simplified Chinese':textCN,
    'Traditional Chinese':textCN_TW,
    'German':textDE,
    'Italian':textIT,
    'French':textFR,
    'Japanese':textJP,
    #to be added
}
